Матожидание и дисперсия

In [2]:
import numpy as np

x = np.array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])
x

array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])

In [3]:
np.std(x)

9.382092977531892

In [8]:
np.std(x, ddof=1)

9.765191977579056

In [4]:

np.var(x)

88.02366863905326

In [6]:
np.var(x, ddof=1)

95.35897435897436

In [5]:

np.sqrt(np.var(x))

9.382092977531892

In [7]:
np.sqrt(np.var(x, ddof=1))

9.765191977579056

Медиана

In [19]:
import numpy as np
z = np.array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])
z


array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])

In [20]:
z.shape


(13,)

In [21]:
z.sort()
z

array([154, 164, 166, 167, 170, 174, 175, 177, 178, 178, 181, 182, 193])

In [23]:
z[6]

175

Первый квартиль

In [24]:
import numpy as np
z = np.array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])
z

array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])

In [25]:
n=len(z)
n

13

In [26]:
z.sort()
z

array([154, 164, 166, 167, 170, 174, 175, 177, 178, 178, 181, 182, 193])

In [28]:
k=25
n*k/100

z[3]

167